(() => {
 const paths={create:'M3 5h12v14H3ZM15 10l6-4v12l-6-4',profile:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-2a8 8 0 0 1 16 0v2',settings:'M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6',home:'M3 10 12 3l9 7v11h-6v-7H9v7H3Z',help:'M4 21V9m16 12V9M2 9q10-12 20 0M4 14h16',heart:'M12 21s-9-5-9-12a5 5 0 0 1 9-3 5 5 0 0 1 9 3c0 7-9 12-9 12Z',prayer:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z',community:'M21 11a8 8 0 0 1-8 8H8l-5 3V6a3 3 0 0 1 3-3h7a8 8 0 0 1 8 8Z',arrow:'M5 12h14m-6-6 6 6-6 6',back:'M19 12H5m6-6-6 6 6 6',save:'M6 3h12v19l-6-4-6 4Z',plus:'M12 5v14M5 12h14',upload:'M12 16V3m-5 5 5-5 5 5M4 15v6h16v-6'};
 const icon=n=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.heart}"/></svg>`;
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const state={page:'home',need:'',language:'English',step:1,filter:'For you',topic:'All',prayed:new Set(),likes:new Set(),saved:new Set(),reply:null,video:null,videoName:'',caption:'',kind:'Testimony',notice:''};
 let userAlias='Quiet Dove';
 let nextId=10;
 const clips=[{id:'r1',kind:'Testimony',alias:'Quiet Cedar',title:'A little hope can change a whole day.',caption:'An everyday reminder that encouragement matters.',sample:true},{id:'r2',kind:'Encouragement',alias:'Morning Light',title:'You do not have to carry it alone.',caption:'Make room for faith, questions, and people who listen.',sample:true}];
 const requests=[{id:'p1',alias:'Still Waters',topic:'Family',body:'My family does not understand my faith, and I feel alone. Please pray for patience, wisdom, and someone I can talk to.',sample:true},{id:'p2',alias:'Quiet Olive',topic:'Displacement',body:'We are trying to begin again after leaving our home. Please pray for peace and a caring community around us.',sample:true},{id:'p3',alias:'Gentle Dawn',topic:'Strength',body:'It has been difficult to hold on to hope this week. Please pray that I find strength for the next step.',sample:true}];
 const posts=[{id:'c1',alias:'Quiet Cedar',topic:'Struggles',body:'Some days I feel like I have to hide the part of me that matters most. Does anyone else find it hard to talk about their faith at home?',sample:true,replies:[{alias:'Still Waters',body:'I relate to that feeling. Thank you for putting it into words.'}]},{id:'c2',alias:'Morning Light',topic:'Questions',body:'Can faith and doubt exist at the same time? I have questions, but I do not want to feel ashamed for asking them.',sample:true,replies:[{alias:'Gentle Dawn',body:'I have questions too. It helps to have a place where we can be honest.'}]},{id:'c3',alias:'Quiet Olive',topic:'Encouragement',body:'Someone checked in on me today without trying to fix everything. Just being heard made a difference.',sample:true,replies:[]}];
 const host=document.getElementById('home');
 host.innerHTML=`<header class="app-top"><span class="brand"><img src="assets/haven-dove.png" alt=""/>Haven</span><span class="desktop-tagline">Faith. Help. Community.</span><div class="header-actions"><button data-page="profile" aria-label="Your profile">${icon('profile')}</button><button data-page="settings" aria-label="Settings">${icon('settings')}</button></div></header><div class="app-scroll" id="app-content"></div><nav class="app-nav" aria-label="Main navigation">${[['home','Home'],['help','FaithBridge'],['create','Post'],['prayer','Prayer'],['community','Community']].map(([key,label])=>`<button data-page="${key}" class="${key==='create'?'dove-tab':''}" aria-label="${key==='create'?'Create a video post':label}" aria-current="${key==='home'?'page':'false'}">${key==='create'?'<span class="dove-button"><img src="assets/haven-dove.png" alt=""/><span aria-hidden="true">+</span></span>':icon(key)}<span>${label}</span></button>`).join('')}</nav><aside class="website-aside" aria-label="Encouragement and community"><section class="website-verse"><p class="overline">A MOMENT OF HOPE</p><blockquote>“God is our refuge and strength, a very present help in trouble.”</blockquote><p>Psalm 46:1 · KJV</p></section><section class="website-connect"><h3>Walk together.</h3><button data-page="prayer">${icon('prayer')}<span><b>Lift someone in prayer</b><small>Stand beside a fellow believer</small></span>${icon('arrow')}</button><button data-page="community">${icon('community')}<span><b>Join the conversation</b><small>Share what is on your heart</small></span>${icon('arrow')}</button><button data-page="help">${icon('help')}<span><b>Find your next step</b><small>Explore FaithBridge resources</small></span>${icon('arrow')}</button></section><p class="website-footnote">Rooted in faith. Connected in hope.</p></aside>`;
 const heading=(label,title,description)=>`<p class="overline">${label}</p><h2 id="home-title" tabindex="-1">${title}</h2><p class="intro">${description}</p>`;
 const avatar=alias=>`<span class="alias-avatar" aria-hidden="true">${esc(alias.split(' ').map(w=>w[0]).join(''))}</span>`;
 const byline=p=>`<div class="byline">${avatar(p.alias)}<span><b>${esc(p.alias)}</b><small>${p.sample?'Illustrative sample':'You · This session'} · ${esc(p.topic||p.kind||'')}</small></span></div>`;
 function home(){const list=clips.filter(c=>state.filter==='For you'||(state.filter==='Testimonies'?c.kind==='Testimony':!c.sample));return `<div class="feed-heading"><h2 id="home-title" tabindex="-1">A little hope.</h2><span>Stories that bring us closer.</span></div><button class="bridge-strip" data-page="help">${icon('help')}<span><b>FaithBridge</b><small>A bridge to the support you need</small></span>${icon('arrow')}</button><div class="feed-tabs" role="group" aria-label="Video feed">${['For you','Testimonies','My videos'].map(f=>`<button data-filter="${f}" aria-pressed="${state.filter===f}">${f}</button>`).join('')}</div>${state.notice?`<p class="session-message" role="status">${esc(state.notice)}</p>`:''}<div class="reels">${list.map((c,i)=>`<article class="reel ${i%2?'reel-blue':''}">${c.url?`<video src="${esc(c.url)}" controls playsinline preload="metadata" aria-label="${esc(c.caption||'Your video')}"></video>`:`<div class="sample-reel"><span class="reel-badge">${c.kind} · Layout sample</span><img src="assets/haven-dove.png" alt=""/><h3>${c.title}</h3><p>Video goes here</p><button data-page="create">Try your own video ${icon('plus')}</button></div>`}<div class="reel-caption"><b>@${esc(c.alias.toLowerCase().replaceAll(' ','_'))}</b><p>${esc(c.caption)}</p><span>${c.sample?'Illustrative content · Not a real testimony':'Only visible in this preview session'}</span></div><div class="reel-actions"><button data-like="${c.id}" aria-label="Like this post" aria-pressed="${state.likes.has(c.id)}">${icon('heart')}</button><button data-save="${c.id}" aria-label="Save this post for this session" aria-pressed="${state.saved.has(c.id)}">${icon('save')}</button></div></article>`).join('')||`<section class="paper-card"><h3>Your stories belong here.</h3><p>Tap the dove to choose a video and try posting it to your preview feed.</p><button class="action" data-page="create">Create a video post ${icon('plus')}</button></section>`}</div>`}
 function helpContent(){if(state.step===2)return `${heading('FAITHBRIDGE','Your next step.','A connection begins with understanding.')}<p class="step">02 / 02 · REVIEW</p><section class="paper-card"><p class="overline">YOUR SELECTION</p><h3>${esc(state.need)}</h3><p>Preferred language: ${esc(state.language)}</p></section><section class="paper-card"><h3>How matching will work</h3><p>FaithBridge will use your circumstances and preferences to search a vetted resource directory. You choose whether to contact an organization.</p></section><div class="notice">Matching is not connected in this design preview. No request has been submitted and no organization has been contacted.</div><button class="action" data-edit>Change my selection ${icon('back')}</button>`;return `${heading('FAITHBRIDGE','Here for your needs.','Start with the kind of support you are looking for.')}<p class="step">01 / 02 · YOUR NEED</p><div class="choice-grid" role="group" aria-label="Type of support">${['Threats or persecution','Displacement','Legal support','Health & wellbeing','Questioning faith?','Not sure yet'].map(n=>`<button class="choice" data-need="${n}" aria-pressed="${state.need===n}">${n}</button>`).join('')}</div><label class="field">Preferred language<select id="language">${['English','Français','Español','العربية','中文'].map(l=>`<option${state.language===l?' selected':''}>${l}</option>`).join('')}</select></label><button class="action" data-continue>Continue ${icon('arrow')}</button><p id="need-error" role="status" class="fine"></p>`}
 function create(){return `${heading('SHARE A LITTLE HOPE','Your story. Your voice.','A testimony, an encouragement, a moment of faith.')}<form id="video-form"><label class="video-picker">${state.video?'<span>Choose a different video</span>':`${icon('upload')}<b>Choose a video</b><span>MP4, WebM or MOV · Up to 100 MB</span>`}<input id="video-file" type="file" accept="video/mp4,video/webm,video/quicktime"/></label>${state.video?`<video class="upload-preview" src="${esc(state.video)}" controls playsinline></video><p class="fine">${esc(state.videoName)}</p>`:''}<label class="field">Post type<select id="video-kind"><option${state.kind==='Testimony'?' selected':''}>Testimony</option><option${state.kind==='Encouragement'?' selected':''}>Encouragement</option></select></label><label class="field">Caption<textarea id="video-caption" maxlength="500" rows="3" placeholder="What would you like to share?">${esc(state.caption)}</textarea></label><div class="notice">Local preview only: your video is not uploaded or shared. Faces, voices, and backgrounds can reveal identity.</div><p class="form-error" id="video-error" role="status"></p><button class="action" type="submit">Post to my preview ${icon('arrow')}</button></form>`}
 function prayer(){return `${heading('HAVEN PRAYER','Carry one another.','Ask for prayer. Stand beside someone in theirs.')}<details class="composer"><summary>${icon('plus')}Share a prayer request</summary><form id="prayer-form"><label class="field">Your request<textarea name="body" required maxlength="1200" rows="4" placeholder="What would you like prayer for?"></textarea></label><p class="fine">Posted as ${esc(userAlias)}. Use sample details; do not include names or exact locations. This stays in this session.</p><button class="action">Add to preview ${icon('arrow')}</button></form></details><p class="feed-note">Sample requests show the experience. New requests are visible only to you until you refresh.</p>${requests.map(p=>`<article class="social-post prayer-post">${byline(p)}<p>${esc(p.body)}</p><button class="prayer-pledge" data-pray="${p.id}" aria-pressed="${state.prayed.has(p.id)}">${icon('prayer')}<span>${state.prayed.has(p.id)?'You prayed for this request':'I prayed for you'}</span></button></article>`).join('')}`}
 function community(){const list=posts.filter(p=>state.topic==='All'||p.topic===state.topic);return `${heading('HAVEN COMMUNITY','Voice your opinions.','Faith, struggles, questions. A conversation with room for you.')}<form class="discussion-composer" id="post-form"><div class="byline">${avatar(userAlias)}<span><b>${esc(userAlias)}</b><small>Your preview alias</small></span></div><label class="sr-only" for="post-body">Share a thought</label><textarea id="post-body" name="body" required maxlength="1200" rows="3" placeholder="What have you been carrying lately?"></textarea><div class="composer-bottom"><label><span class="sr-only">Topic</span><select name="topic"><option>Struggles</option><option>Questions</option><option>Encouragement</option></select></label><button type="submit">Post</button></div></form><p class="feed-note">Illustrative discussions · Your posts and replies stay in this session. No live anonymous messaging.</p><div class="chips" role="group" aria-label="Discussion topics">${['All','Struggles','Questions','Encouragement'].map(t=>`<button data-topic="${t}" aria-pressed="${state.topic===t}">${t}</button>`).join('')}</div>${list.map(p=>`<article class="social-post">${byline(p)}<p>${esc(p.body)}</p><div class="post-actions"><button data-like="${p.id}" aria-pressed="${state.likes.has(p.id)}">${icon('heart')}<span>${state.likes.has(p.id)?'Supported':'Support'}</span></button><button data-reply="${p.id}" aria-expanded="${state.reply===p.id}">${icon('community')}<span>${p.replies.length} ${p.replies.length===1?'reply':'replies'}</span></button></div>${state.reply===p.id?`<div class="replies">${p.replies.map(r=>`<div class="reply"><b>${esc(r.alias)}</b><p>${esc(r.body)}</p></div>`).join('')}<form class="reply-form" data-reply-form="${p.id}"><label class="sr-only" for="reply-${p.id}">Your reply</label><textarea id="reply-${p.id}" name="body" required maxlength="600" rows="2" placeholder="Reply with kindness…"></textarea><button type="submit">Reply as ${esc(userAlias)}</button></form></div>`:''}</article>`).join('')||'<p class="intro">No posts in this topic yet. Start the conversation above.</p>'}`}
 const organizations=[
  {name:'Open Doors',tag:'Persecuted Church',description:'Explore country profiles and learn about support for persecuted Christians worldwide.',url:'https://www.opendoors.org/en-US/',letters:'OD'},
  {name:'The Voice of the Martyrs',tag:'Prayer & encouragement',description:'Find prayer guides, testimonies, and ways to support Christians facing persecution.',url:'https://www.persecution.com/',letters:'VM'},
  {name:'Global Christian Relief',tag:'Relief & support',description:'Learn about relief efforts and stories from Christian communities facing persecution.',url:'https://globalchristianrelief.org/',letters:'GR'}
 ];
 function resources(){return `<section class="organization-resources" aria-labelledby="resources-title"><p class="overline">BUILDING THE BRIDGE</p><h3 id="resources-title">Organizations & resources</h3><p class="resource-intro">Explore organizations serving Christians facing persecution.</p><p class="resource-note">Public resources · Haven partnerships and direct referrals are not yet established.</p><div class="organization-list">${organizations.map(o=>`<article class="organization-card"><div class="organization-top"><span class="organization-mark" aria-hidden="true">${o.letters}</span><span><small>${o.tag}</small><h4>${o.name}</h4></span></div><p>${o.description}</p><a href="${o.url}" target="_blank" rel="noopener noreferrer">Explore resources <span aria-hidden="true">↗</span><span class="sr-only"> from ${o.name} (opens in a new tab)</span></a></article>`).join('')}</div></section>`}
 function help(){return `<div class="needs-panel">${helpContent()}</div>${resources()}`}
 function profile(){return `${heading('YOUR HAVEN','Your profile.','Your place in the community.')}<section class="profile-card">${avatar(userAlias)}<h3>${esc(userAlias)}</h3><p>Your community name</p></section><div class="profile-stats"><div><b>${clips.filter(c=>!c.sample).length}</b><span>Videos</span></div><div><b>${posts.filter(p=>!p.sample).length}</b><span>Discussions</span></div><div><b>${requests.filter(p=>!p.sample).length}</b><span>Prayer requests</span></div></div><button class="account-row" data-my-videos>${icon('create')}<span>My videos</span>${icon('arrow')}</button><button class="account-row" data-page="settings">${icon('settings')}<span>Settings</span>${icon('arrow')}</button><p class="fine">Your activity is available for this preview session. No account has been created.</p>`}
 function settings(){return `${heading('YOUR HAVEN','Settings.','Make Haven feel more like you.')}<section class="paper-card"><h3>FaithBridge preferences</h3><label class="field">Preferred support language<select id="language">${['English','Français','Español','العربية','中文'].map(l=>`<option${state.language===l?' selected':''}>${l}</option>`).join('')}</select></label><p class="settings-hint">Used for your FaithBridge support selection.</p><p id="settings-feedback" class="settings-feedback" role="status"></p></section><button class="account-row" data-page="profile">${icon('profile')}<span>Your profile</span>${icon('arrow')}</button><button class="account-row" data-replay-opening>${icon('back')}<span>Replay Haven intro</span>${icon('arrow')}</button><p class="fine">Preferences apply to this preview session.</p>`}
 const views={home,help,create,prayer,community,profile,settings};
 function render(focus=false){host.dataset.view=state.page;const content=document.getElementById('app-content');content.querySelectorAll('video').forEach(v=>v.pause());content.innerHTML=views[state.page]();content.classList.toggle('is-feed',state.page==='home');host.querySelectorAll('.app-nav [data-page], .header-actions [data-page]').forEach(b=>b.setAttribute('aria-current',b.dataset.page===state.page?'page':'false'));if(focus){content.scrollTop=0;document.getElementById('home-title').focus({preventScroll:true})}}
 function navigate(page){state.page=page;state.reply=null;render(true)}
 host.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
  if(b.dataset.page)navigate(b.dataset.page);
  else if(b.hasAttribute('data-my-videos')){state.filter='My videos';navigate('home')}
  else if(b.hasAttribute('data-replay-opening')){host.querySelectorAll('video').forEach(v=>v.pause());replay()}
  else if(b.dataset.need){state.need=b.dataset.need;host.querySelectorAll('[data-need]').forEach(x=>x.setAttribute('aria-pressed',x===b))}
  else if(b.hasAttribute('data-continue')){if(!state.need){document.getElementById('need-error').textContent='Choose a support type to continue.';return}state.step=2;render(true)}
  else if(b.hasAttribute('data-edit')){state.step=1;render(true)}
  else if(b.dataset.filter){state.filter=b.dataset.filter;render();host.querySelector(`[data-filter="${state.filter}"]`).focus()}
  else if(b.dataset.topic){state.topic=b.dataset.topic;render();host.querySelector(`[data-topic="${state.topic}"]`).focus()}
  else if(b.dataset.pray){const id=b.dataset.pray;state.prayed.has(id)?state.prayed.delete(id):state.prayed.add(id);b.setAttribute('aria-pressed',state.prayed.has(id));b.querySelector('span').textContent=state.prayed.has(id)?'You prayed for this request':'I prayed for you'}
  else if(b.dataset.like||b.dataset.save){const save=!!b.dataset.save,id=save?b.dataset.save:b.dataset.like,set=save?state.saved:state.likes;set.has(id)?set.delete(id):set.add(id);b.setAttribute('aria-pressed',set.has(id));if(b.querySelector('span'))b.querySelector('span').textContent=set.has(id)?'Supported':'Support'}
  else if(b.dataset.reply){state.reply=state.reply===b.dataset.reply?null:b.dataset.reply;const top=document.getElementById('app-content').scrollTop;render();document.getElementById('app-content').scrollTop=top;host.querySelector(`[data-reply="${b.dataset.reply}"]`).focus()}
 });
 host.addEventListener('input',e=>{if(e.target.id==='video-caption')state.caption=e.target.value;if(e.target.matches('textarea'))e.target.setCustomValidity('')});
 host.addEventListener('change',e=>{if(e.target.id==='language'){state.language=e.target.value;const feedback=document.getElementById('settings-feedback');if(feedback)feedback.textContent='Support language updated.';}if(e.target.id==='video-kind')state.kind=e.target.value;if(e.target.id==='video-file'){const file=e.target.files[0];if(!file)return;if(!file.type.startsWith('video/')||file.size>100*1024*1024){document.getElementById('video-error').textContent='Choose a video smaller than 100 MB.';return}if(state.video)URL.revokeObjectURL(state.video);state.video=URL.createObjectURL(file);state.videoName=file.name;render()}});
 host.addEventListener('error',e=>{if(e.target.matches('video')){const p=document.createElement('p');p.className='form-error';p.textContent='This browser could not play the video. Try an MP4 or WebM file.';e.target.replaceWith(p)}},true);
 host.addEventListener('submit',e=>{e.preventDefault();const form=e.target;
  if(form.id==='video-form'){if(!state.video){document.getElementById('video-error').textContent='Choose a video first.';return}clips.unshift({id:'r'+nextId++,alias:userAlias,kind:state.kind,caption:state.caption||'A moment of hope.',url:state.video,sample:false});state.video=null;state.videoName='';state.caption='';state.filter='My videos';state.notice='Your video was added to this preview. It has not been shared publicly.';navigate('home');return}
  const data=new FormData(form),body=String(data.get('body')||'').trim();if(!body){form.querySelector('textarea').setCustomValidity('Write a few words first.');form.querySelector('textarea').reportValidity();return}form.querySelector('textarea').setCustomValidity('');
  if(form.id==='prayer-form'){requests.unshift({id:'p'+nextId++,alias:userAlias,topic:'Prayer request',body,sample:false});render(true)}
  else if(form.id==='post-form'){posts.unshift({id:'c'+nextId++,alias:userAlias,topic:String(data.get('topic')),body,sample:false,replies:[]});state.topic='All';render(true)}
  else if(form.dataset.replyForm){posts.find(p=>p.id===form.dataset.replyForm).replies.push({alias:userAlias,body});const top=document.getElementById('app-content').scrollTop;render();document.getElementById('app-content').scrollTop=top}
 });
 window.resetHavenHome=alias=>{userAlias=alias||'Quiet Dove';state.notice=alias?'Welcome, '+userAlias+'. You are exploring the preview; no account was created.':'';navigate('home')};
 render();
})();
